### ISSUE TITLE
Cannot find module 'events' in Next.js App while implementing masstransit.

### ISSUE THREAD

**Issue by rutwik-fale-amla** [MassTransit/MassTransit-JS#12]
I am using the Next.js application and have just started implementing the MassTransit in the application.
But I'm getting this error.

`Error: Cannot find module 'events'
    at webpackEmptyContext (D:\demo\MTNodejs\next-message-broker\.next\server\app\broker\page.js:22:10)
    at eval (webpack-internal:///(rsc)/./node_modules/masstransit-rabbitmq/dist/bus.js:184:36)
    at eval (webpack-internal:///(rsc)/./node_modules/masstransit-rabbitmq/dist/bus.js:161:17)
    at eval (webpack-internal:///(rsc)/./node_modules/masstransit-rabbitmq/dist/bus.js:179:3)
    at (rsc)/./node_modules/masstransit-rabbitmq/dist/bus.js (D:\demo\MTNodejs\next-message-broker\.next\server\vendor-chunks\masstransit-rabbitmq.js:30:1)
    at __webpack_require__ (D:\demo\MTNodejs\next-message-broker\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./app/broker/page.tsx:11:78)
    at (rsc)/./app/broker/page.tsx (D:\demo\MTNodejs\next-message-broker\.next\server\app\broker\page.js:301:1)
    at Function.__webpack_require__ (D:\demo\MTNodejs\next-message-broker\.next\server\webpack-runtime.js:33:42)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
    at async eh (D:\demo\MTNodejs\next-message-broker\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:22:152341)    
    at async eU (D:\demo\MTNodejs\next-message-broker\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:22:156455)    
    at async eB (D:\demo\MTNodejs\next-message-broker\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:22:156930)    
    at async eB (D:\demo\MTNodejs\next-message-broker\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:22:157061)    
    at async eB (D:\demo\MTNodejs\next-message-broker\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:22:157061)    
    at async eH (D:\demo\MTNodejs\next-message-broker\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:22:160470)    
    at async D:\demo\MTNodejs\next-message-broker\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:22:160942 {       
  digest: '3225388874',
  page: '/broker'`

here is my **package.json** file:

`{
  "name": "next-message-broker",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "masstransit-rabbitmq": "^0.1.3",
    "react": "latest",
    "react-dom": "latest",
    "next": "latest"
  },
  "devDependencies": {
    "typescript": "latest",
    "@types/react": "latest",
    "@types/node": "latest",
    "@types/react-dom": "latest"
  }
}
`

Here is the **code sample** where the actual error is occurring:

`import React from 'react';
import {MessageType} from 'masstransit-rabbitmq/dist/messageType';
import masstransit from 'masstransit-rabbitmq';

const broker = () => {
    
MessageType.setDefaultNamespace('Contracts');

const bus = masstransit(); // cause error
    
return (

<div>broker</div>
    )}
export default broker`

**Comment by phatboyg** [comment]
I don't see how this is related to this package.

**Comment by rutwik-fale-amla** [comment]
![image](https://github.com/MassTransit/MassTransit-JS/assets/114402610/4a683939-f621-478d-9f12-90af63c5fd74)

You can see in the highlighted text that I have used MassTransit and this line only caused the mentioned error.
